### ISSUE TITLE
re: enhanced 3d cursor

### ISSUE THREAD

**Issue by meta-androcto** [dairin0d/enhanced-3d-cursor#1] opened 2016-03-05 04:22 UTC
hi, there;s a bug report here: https://developer.blender.org/T47609
any chance you can have a look please.
thanks.

**Comment by dairin0d** [comment] 2016-03-05 17:28
Sorry for the delay.
The problem was actually caused by the change of the ray_cast() return value in Blender 2.77, so snapping didn't work at all.
It should be fixed now.

**Closed as completed by dairin0d** 2016-03-05 17:28 UTC
